apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcbankweb-deployment
spec:
  selector:
    matchLabels:
      app: abcbankweb
  replicas: 1
  template:
    metadata:
      labels:
        app: abcbankweb
    spec:
      containers:
      - name: abcbankweb
        image: nogayama/abcbankweb:v2
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
